version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - HOST=${HOST}
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    networks:
      - backend
    stdin_open: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - HOST=${HOST}
      - CORS_ORIGIN_URL=${CORS_ORIGIN_URL}
      - MONGODB_URL=${MONGODB_URL}
      - NODE_ENV=production
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mongo:4.4.1-bionic
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - backend
    volumes:
      - database_data:/data/db

networks:
  backend:
    driver: bridge

volumes:
  database_data:
