version: "2"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on: 
      - db
  db:
    image: mongo:3
    # volumes links storage from the localmachine to the storage on the mongo container
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"