version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=dev
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json