version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - NODE_ENV=production
      - API_PORT=${API_PORT}
    networks:
      - backend
    depends_on:
      - db
  db:
    image: mongo:4.4.1-bionic
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - backend
    volumes:
      - database_data:/data/db

networks:
  backend:
    driver: bridge

volumes:
  database_data: